SchoolRegister.Web/Controllers/GroupController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;
using SchoolRegister.ViewModels.VMs;
using SchoolRegister.Web.Models;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Admin,Teacher")]
    public class GroupController : BaseController<GroupController>
    {
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        private readonly IStudentService _studentService;
        private readonly ISubjectService _subjectService;

        public GroupController(IMapper mapper, IGroupService groupService, IStudentService studentService, ISubjectService subjectService,
            IStringLocalizer<GroupController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _mapper = mapper;
            _groupService = groupService;
            _studentService = studentService;
            _subjectService = subjectService;
        }

        [Authorize(Roles = "Admin,Teacher,Parent,Student")]
        public IActionResult Index()
        {
            var groupsVM = _groupService.GetGroups();
            return View(groupsVM);
        }

        public IActionResult Details(int id)
        {
            GroupVM groupVM = _groupService.GetGroup(g => g.Id == id);
            if(groupVM != null)
            {
                return View(groupVM);
            }
            return View("Error");
        }

        public IActionResult CreateOrUpdate(int? id = null)
        {
            if(id.HasValue)
            {
                var groupVM = _groupService.GetGroup(g => g.Id == id.Value);
                ViewBag.ActionType = "Edit";
                var groupDTO = _mapper.Map<GroupForCreateOrUpdateDTO>(groupVM);
                return View(groupDTO);
            }
            ViewBag.ActionType = "Add";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrUpdate(GroupForCreateOrUpdateDTO groupForCreateOrUpdateDTO)
        {
            if (ModelState.IsValid)
            {
                if (_groupService.CreateOrUpdateGroup(groupForCreateOrUpdateDTO) == null)
                    return View("Error", new ErrorViewModel() { Description = "This group already exists!" });
                return RedirectToAction("Index");
            }
            return View();
        }
        
    }
}

SchoolRegister.Web/Controllers/StudentGroupController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Admin,Teacher")]
    public class StudentGroupController : BaseController<StudentGroupController>
    {
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        private readonly IStudentService _studentService;
        private readonly IStudentGroupService _studentGroupService;

        public StudentGroupController(IMapper mapper, IGroupService groupService, IStudentService studentService, IStudentGroupService studentGroupService,
            IStringLocalizer<StudentGroupController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _mapper = mapper;
            _groupService = groupService;
            _studentService = studentService;
            _studentGroupService = studentGroupService;
        }

        public IActionResult AttachStudentToGroup(int id)
        {
            var studentsVM = _studentService.GetStudents(s => s.GroupId  == null || s.GroupId == 0);
            ViewBag.StudentsSelectList = _mapper.Map<IEnumerable<SelectListItem>>(studentsVM);

            var groupVM = _groupService.GetGroup(g => g.Id == id);
            if (groupVM == null)
            {
                return View("Error");
            }
            ViewBag.GroupName = groupVM.Name;

            return View(new AttachDetachStudentWithGroupDTO() { GroupId = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AttachStudentToGroup(AttachDetachStudentWithGroupDTO attachDetachStudentWithGroupDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var studentVM = _studentGroupService.AttachStudentWithGroup(attachDetachStudentWithGroupDTO);
                    if (studentVM != null)
                    {
                        return RedirectToAction("Details", "Group", new { id = attachDetachStudentWithGroupDTO.GroupId });
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }

            }

            return View();
        }

        public IActionResult DetachStudentFromGroup(int id)
        {
            var groupVM = _groupService.GetGroup(g => g.Id == id);
            if (groupVM == null)
            {
                return View("Error");
            }
            ViewBag.GroupName = groupVM.Name;

            var studentsVM = groupVM.Students;
            ViewBag.StudentsSelectList = _mapper.Map<IEnumerable<SelectListItem>>(studentsVM);


            return View(new AttachDetachStudentWithGroupDTO() { GroupId = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DetachStudentFromGroup(AttachDetachStudentWithGroupDTO attachDetachStudentWithGroupDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var studentVM = _studentGroupService.DetachStudentFromGroup(attachDetachStudentWithGroupDTO);
                    if (studentVM != null)
                    {
                        return RedirectToAction("Details", "Group", new { id = attachDetachStudentWithGroupDTO.GroupId });
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }

            }

            return View();
        }
    }
}

SchoolRegister.Web/Controllers/SubjectGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Admin,Teacher")]
    public class SubjectGroupController : BaseController<SubjectGroupController>
    {
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        private readonly ISubjectService _subjectService;
        private readonly ISubjectGroupService _subjectGroupService;

        public SubjectGroupController(IMapper mapper, IGroupService groupService, ISubjectService subjectService, ISubjectGroupService subjectGroupService,
            IStringLocalizer<SubjectGroupController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _mapper = mapper;
            _groupService = groupService;
            _subjectService = subjectService;
            _subjectGroupService = subjectGroupService;
        }
        public IActionResult AttachSubjectToGroup(int id)
        {
            var groupVM = _groupService.GetGroup(g => g.Id == id);
            if (groupVM == null)
            {
                return View("Error");
            }
            ViewBag.GroupName = groupVM.Name;

            var subjectsVM = _subjectService.GetSubjects().Where(s => groupVM.Subjects.All(x => x.Id != s.Id));
            ViewBag.SubjectsSelectList = _mapper.Map<IEnumerable<SelectListItem>>(subjectsVM);

            return View(new AttachDetachSubjectWithGroupDTO { GroupId = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AttachSubjectToGroup(AttachDetachSubjectWithGroupDTO attachDetachSubjectWithGroupDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var groupVM = _subjectGroupService.AttachSubjectWithGroup(attachDetachSubjectWithGroupDTO);
                    if (groupVM != null)
                    {
                        return RedirectToAction("Details", "Group" , new { id = attachDetachSubjectWithGroupDTO.GroupId });
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }

            }

            return View();
        }

        public IActionResult DetachSubjectFromGroup(int id)
        {
            var groupVM = _groupService.GetGroup(g => g.Id == id);
            if (groupVM == null)
            {
                return View("Error");
            }
            ViewBag.GroupName = groupVM.Name;

            var subjectsVM = groupVM.Subjects;
            ViewBag.SubjectsSelectList = _mapper.Map<IEnumerable<SelectListItem>>(subjectsVM);

            return View(new AttachDetachSubjectWithGroupDTO { GroupId = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DetachSubjectFromGroup(AttachDetachSubjectWithGroupDTO attachDetachSubjectWithGroupDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var groupVM = _subjectGroupService.DetachSubjectFromGroup(attachDetachSubjectWithGroupDTO);
                    if (groupVM != null)
                    {
                        return RedirectToAction("Details", "Group", new { id = attachDetachSubjectWithGroupDTO.GroupId });
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }

            }

            return View();
        }
    }
}

SchoolRegister.Web/Views/Group/CreateOrUpdate.cshtml
@model SchoolRegister.ViewModels.DTOs.GroupForCreateOrUpdateDTO
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = ViewBag.ActionType + " " + Localizer["Group"];
}


<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">@Localizer["Name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Localizer["BackToList"]</a>
</div>

SchoolRegister.Web/Views/Group/Details.cshtml
@model SchoolRegister.ViewModels.VMs.GroupVM
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Details"].Value + " - " + Localizer["Group"].Value + " " + Model.Name;
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label>@Localizer["Name"]</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            <label>@Localizer["Students"]</label>
        </dt>
        <dd class="col-sm-10">
            @foreach (var student in Model.Students)
            {
                @Html.DisplayFor(modelItem => student.FirstName)
                @Html.Raw(" ");
                @Html.DisplayFor(modelItem => student.LastName)
                @Html.Raw(", ");

            }
        </dd>
        <dt class="col-sm-2">
            <label>@Localizer["Subjects"]</label>
        </dt>
        <dd class="col-sm-10">
            @foreach (var subject in Model.Subjects)
            {
                @Html.DisplayFor(modelItem => subject.Name)
                @Html.Raw(", ");

            }
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Index">@Localizer["BackToList"]</a>
</div>

SchoolRegister.Web/Views/Group/Index.cshtml
@model IEnumerable<SchoolRegister.ViewModels.VMs.GroupVM>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Groups"].Value;
}

<h1>@ViewData["Title"]</h1>

@if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
{
    <p>
        <a asp-action="CreateOrUpdate">@Localizer["CreateNew"]</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                <label>@Localizer["Name"]</label>
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink(Localizer["Edit"].Value, "CreateOrUpdate", new { id = item.Id }) |
                    @Html.ActionLink(Localizer["Details"].Value, "Details", new { id = item.Id }) |
                    @Html.ActionLink(Localizer["AttachStudent"].Value, "AttachStudentToGroup", "StudentGroup", new { id = item.Id }) |
                    @Html.ActionLink(Localizer["DetachStudent"].Value, "DetachStudentFromGroup", "StudentGroup", new { id = item.Id }) |
                    @Html.ActionLink(Localizer["AttachSubject"].Value, "AttachSubjectToGroup", "SubjectGroup", new { id = item.Id }) |
                    @Html.ActionLink(Localizer["DetachSubject"].Value, "DetachSubjectFromGroup", "SubjectGroup", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>