SchoolRegister.Web/Controllers/ChatController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.VMs;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SchoolRegister.Web.Controllers
{
    [Authorize]
    public class ChatController : BaseController<ChatController>
    {
        private IStudentService _studentService;
        private IGroupService _groupService;
        private IMapper _mapper;

        public ChatController(IStringLocalizer<ChatController> localizer, ILoggerFactory loggerFactory, 
            IStudentService studentService, IGroupService groupService, IMapper mapper) : base(localizer, loggerFactory)
        {
            _studentService = studentService;
            _groupService = groupService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var students = _studentService.GetStudents().ToList();
            students.Add(new StudentVM()
            {
                FirstName = "All students",
            });

            var chatGroups = _groupService.GetGroups();
            var studentsListItems = _mapper.Map<IEnumerable<SelectListItem>>(students);
            var chatGroupListItems = _mapper.Map<IEnumerable<SelectListItem>>(chatGroups);

            return View(new Tuple<IEnumerable<SelectListItem>, IEnumerable<SelectListItem>>(studentsListItems, chatGroupListItems));
        }
    }
}

SchoolRegister.Web/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.BLL.Entities;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;
using SchoolRegister.ViewModels.VMs;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Admin, Teacher")]
    public class EmailController : BaseController<EmailController>
    {
        private readonly IStudentService _studentService;
        private readonly IEmailService _emailService;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;

        public EmailController(IStudentService studentService, IEmailService emailService, UserManager<User> userManager, IMapper mapper,
            IStringLocalizer<EmailController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _studentService = studentService;
            _emailService = emailService;
            _userManager = userManager;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var studentsVM = _studentService.GetStudents();
            ViewBag.StudentsSelectList = _mapper.Map<IEnumerable<SelectListItem>>(studentsVM);

            var user = _userManager.GetUserAsync(User).Result;
            return View(new SendEmailToParentDTO() { SenderId = user.Id });
        }

        [HttpPost]
        public IActionResult Index(SendEmailToParentDTO sendEmailToParentDTO)
        {
            if (ModelState.IsValid)
            {
                /*if(_emailService.SendEmailToParent(sendEmailToParentDTO))
                {*/
                    return RedirectToAction("Details", new
                    {
                        SenderId = sendEmailToParentDTO.SenderId,
                        StudentId = sendEmailToParentDTO.StudentId,
                        Title = sendEmailToParentDTO.Title,
                        Content = sendEmailToParentDTO.Content
                    });
                /*
                }*/
            }
            return View("Error");
        }

        public IActionResult Details(SendEmailToParentDTO sendEmailToParentDTO)
        {
            try
            {
                var student = _userManager.FindByIdAsync(sendEmailToParentDTO.StudentId.ToString()).Result as Student;
                var parent = _userManager.FindByIdAsync(student.ParentId.ToString()).Result as Parent;
                var sender = _userManager.FindByIdAsync(sendEmailToParentDTO.SenderId.ToString()).Result;
                var emailToDisplay = new SentEmailVM()
                {
                    SenderName = $"{sender.FirstName} {sender.LastName}",
                    ParentName = $"{parent.FirstName} {parent.LastName}",
                    StudentName = $"{student.FirstName} {student.LastName}",
                    Title = sendEmailToParentDTO.Title,
                    Content = sendEmailToParentDTO.Content
                };
                return View(emailToDisplay);
            }
            catch(Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

SchoolRegister.Web/Controllers/GroupController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;
using SchoolRegister.ViewModels.VMs;
using SchoolRegister.Web.Models;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Admin,Teacher")]
    public class GroupController : BaseController<GroupController>
    {
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        private readonly IStudentService _studentService;
        private readonly ISubjectService _subjectService;

        public GroupController(IMapper mapper, IGroupService groupService, IStudentService studentService, ISubjectService subjectService,
            IStringLocalizer<GroupController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _mapper = mapper;
            _groupService = groupService;
            _studentService = studentService;
            _subjectService = subjectService;
        }

        [Authorize(Roles = "Admin,Teacher,Parent,Student")]
        public IActionResult Index()
        {
            var groupsVM = _groupService.GetGroups();
            return View(groupsVM);
        }

        public IActionResult Details(int id)
        {
            GroupVM groupVM = _groupService.GetGroup(g => g.Id == id);
            if(groupVM != null)
            {
                return View(groupVM);
            }
            return View("Error");
        }

        public IActionResult CreateOrUpdate(int? id = null)
        {
            if(id.HasValue)
            {
                var groupVM = _groupService.GetGroup(g => g.Id == id.Value);
                ViewBag.ActionType = "Edit";
                var groupDTO = _mapper.Map<GroupForCreateOrUpdateDTO>(groupVM);
                return View(groupDTO);
            }
            ViewBag.ActionType = "Add";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrUpdate(GroupForCreateOrUpdateDTO groupForCreateOrUpdateDTO)
        {
            if (ModelState.IsValid)
            {
                if (_groupService.CreateOrUpdateGroup(groupForCreateOrUpdateDTO) == null)
                    return View("Error", new ErrorViewModel() { Description = "This group already exists!" });
                return RedirectToAction("Index");
            }
            return View();
        }
        
    }
}

SchoolRegister.Web/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.BLL.Entities;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;
using SchoolRegister.ViewModels.VMs;
using SchoolRegister.Web.Extensions;
using SchoolRegister.Web.Models;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles ="Admin, Teacher")]
    public class SubjectController : BaseController<SubjectController>
    {
        private readonly ISubjectService _subjectService;
        private readonly ITeacherService _teacherService;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;

        public SubjectController(ISubjectService subjectService, ITeacherService teacherService, UserManager<User> userManager, IMapper mapper,
            IStringLocalizer<SubjectController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _subjectService = subjectService;
            _teacherService = teacherService;
            _userManager = userManager;
            _mapper = mapper;
        }
        
        public IActionResult Index(string filterValue = null)
        {
            Expression<Func<Subject, bool>> filterPredicate = null;
            if(!string.IsNullOrWhiteSpace(filterValue))
            {
                filterPredicate = x => x.Name.Contains(filterValue);
            }

            bool isAjax = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";

            var user = _userManager.GetUserAsync(User).Result;
            IEnumerable<SubjectVM> subjectsVM = null;
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                subjectsVM = _subjectService.GetSubjects(filterPredicate);
            }
            else if (_userManager.IsInRoleAsync(user, "Teacher").Result)
            {
                var teacher = _userManager.GetUserAsync(User).Result as Teacher;

                Expression<Func<Subject, bool>> filterByTeacher = x => x.TeacherId == teacher.Id;

                var finalFilter = filterPredicate != null ?
                    Expression.Lambda<Func<Subject, bool>>(
                        Expression.AndAlso(filterPredicate.Body,
                        new ExpressionParameterReplacer(filterByTeacher.Parameters, filterPredicate.Parameters)
                        .Visit(filterByTeacher.Body)),
                        filterPredicate.Parameters) : filterByTeacher;

                subjectsVM = _subjectService.GetSubjects(finalFilter);
            }

            if(subjectsVM == null)
            {
                return View("Error");
            }

            if(isAjax)
            {
                return PartialView("_SubjectsTablePartial", subjectsVM);
            }

            return View(subjectsVM);

        }

        public IActionResult Details(int id)
        {
            var subjectVM = _subjectService.GetSubject(x => x.Id == id);
            if (subjectVM == null)
                return View("Error");
            return View(subjectVM);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CreateOrUpdateSubject(int? id = null)
        {
            var teachersVM = _teacherService.GetTeachers();
            ViewBag.TeachersSelectList = _mapper.Map<IEnumerable<SelectListItem>>(teachersVM);

            if (id.HasValue)
            {
                var subjectVM = _subjectService.GetSubject(x => x.Id == id);
                if(subjectVM == null)
                {
                    return View("Error");
                }
                ViewBag.ActionType = _localizer["Edit"];
                return View(_mapper.Map<SubjectForCreateOrUpdateDTO>(subjectVM));
            }
            ViewBag.ActionType = _localizer["Add"];
            return View();
        }

        [HttpPost]
        [Authorize(Roles="Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrUpdateSubject(SubjectForCreateOrUpdateDTO subjectForCreateOrUpdateDTO)
        {
            if(ModelState.IsValid)
            {
                if (_subjectService.CreateOrUpdate(subjectForCreateOrUpdateDTO) != null)
                    return RedirectToAction("Index");
                return View("Error",new ErrorViewModel() { Description = _localizer["This subject already exists"] }); //already exists with this name
            }
            return View("CreateOrUpdateSubject");
        }
    }
}

SchoolRegister.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolRegister.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolRegister.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>

                        @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">@Localizer["Subjects"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="Index">@Localizer["Groups"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="Index">@Localizer["Email"]</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">@Localizer["Students"]</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">@Localizer["Chat"]</a>
                            </li>
                        }


                    </ul>
                </div>

                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SchoolRegister.Web - Maria Bereszyńska
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SchoolRegister.Web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{ 
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName }).ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" method="post"
          class="form-horizontal" role="form">
        <select name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems" onchange="this.form.submit()">
        </select>
    </form>
</div>