SchoolRegister.Web/Controllers/GradeController.cs
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.BLL.Entities;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.DTOs;
using SchoolRegister.ViewModels.VMs;

namespace SchoolRegister.Web.Controllers
{
    [Authorize]
    public class GradeController : BaseController<GradeController>
    {
        private readonly IMapper _mapper;
        private readonly IGradeService _gradeService;
        private readonly ISubjectService _subjectService;
        private readonly IStudentService _studentService;
        private readonly UserManager<User> _userManager;

        public GradeController(IMapper mapper, IGradeService gradeService, ISubjectService subjectService, IStudentService studentService,
            UserManager<User> userManager, IStringLocalizer<GradeController> localizer, ILoggerFactory loggerFactory) : base(localizer, loggerFactory)
        {
            _mapper = mapper;
            _gradeService = gradeService;
            _subjectService = subjectService;
            _studentService = studentService;
            _userManager = userManager;
        }

        public IActionResult Index(int? id = null)
        {
            if(!id.HasValue)
            {
                return View("Error");
            }
            var user = _userManager.GetUserAsync(User).Result;
            return View(_gradeService.GetGradesReportForStudent(new GetGradesDTO { GetterUserId = user.Id, StudentId = id.Value }));
        }

        [Authorize(Roles ="Teacher")]
        public IActionResult Create(int? id = null)
        {
            if (!id.HasValue)
            {
                return View("Error");
            }

            var teacher = _userManager.GetUserAsync(User).Result as Teacher;
            var gradeForCreate = new GradeForStudentAddDTO() { TeacherId = teacher.Id };

            var subjectsVM = _mapper.Map<IEnumerable<SubjectVM>>(teacher.Subjects);
            ViewBag.SubjectsSelectList = _mapper.Map<IEnumerable<SelectListItem>>(subjectsVM);

            var studentVM = _studentService.GetStudent(x => x.Id == id.Value);
            ViewBag.Student = studentVM;

            return View(gradeForCreate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public IActionResult Create(GradeForStudentAddDTO gradeForStudentAddDTO)
        {
            if (ModelState.IsValid)
            {
                _gradeService.AddGradeToStudent(gradeForStudentAddDTO);
                return RedirectToAction("Index", new { id = gradeForStudentAddDTO.StudentId });
            }
            return View();
        }
    }
}

SchoolRegister.Web/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.BLL.Entities;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.VMs;
using SchoolRegister.Web.Extensions;

namespace SchoolRegister.Web.Controllers
{
    public class StudentController : BaseController<StudentController>
    {
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;
        private readonly IStudentService _studentService;
        private readonly IGroupService _groupService;
        private readonly ISubjectService _subjectService;
        public StudentController(UserManager<User> userManager, IMapper mapper, IStudentService studentService,
            IGroupService groupService, ISubjectService subjectService,
            IStringLocalizer<StudentController> stringLocalizer, ILoggerFactory loggerFactory) : base(stringLocalizer, loggerFactory)
        {
            _userManager = userManager;
            _mapper = mapper;
            _studentService = studentService;
            _groupService = groupService;
            _subjectService = subjectService;
        }
        public IActionResult Index(string filterValue = null)
        {
            Expression<Func<Student, bool>> filterPredicate = null;
            if (!string.IsNullOrWhiteSpace(filterValue))
            {
                filterPredicate = x => (x.FirstName + " " + x.LastName).Contains(filterValue);
            }
            var user = _userManager.GetUserAsync(User).Result;
            IEnumerable<StudentVM> studentsVM = null;

            if (_userManager.IsInRoleAsync(user, "Student").Result)
            {
                studentsVM = new List<StudentVM> { _mapper.Map<StudentVM>(user) };
            }
            else if (_userManager.IsInRoleAsync(user, "Parent").Result)
            {
                studentsVM = _studentService.GetStudents(s => s.ParentId == user.Id);
            }
            else if (_userManager.IsInRoleAsync(user, "Teacher").Result)
            {
                var teacher = user as Teacher;

                Expression<Func<Student, bool>> filterByTeacherPredicate =
                    s => s.Group.SubjectGroups.Any(sg => teacher.Subjects.Select(sub => sub.Id).Contains(sg.SubjectId));

                var finalFilter = filterPredicate != null ?
                    Expression.Lambda<Func<Student, bool>>(
                    Expression.AndAlso(filterPredicate.Body,
                    new ExpressionParameterReplacer(filterByTeacherPredicate.Parameters, filterPredicate.Parameters)
                    .Visit(filterByTeacherPredicate.Body)),
                    filterPredicate.Parameters) : filterByTeacherPredicate;

                studentsVM = _studentService.GetStudents(finalFilter);
            }
            else if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                studentsVM = _studentService.GetStudents(filterPredicate);
            }

            if (studentsVM == null)
            {
                return View("Error");
            }

            bool isAjax = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";
            if (isAjax)
            {
                return PartialView("_StudentsTablePartial", studentsVM);
            }
            return View(studentsVM);
        }
    }
}

SchoolRegister.Web/Views/Student/Index.cshtml
@model IEnumerable<SchoolRegister.ViewModels.VMs.StudentVM>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Students"];
}

<h1>@ViewData["Title"]</h1>

@if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
    {
<div class="row">
    <div class="col-lg-4">
        <input id="students-filter-input" class="form-control" type="text" placeholder="@Localizer["Filter"]" />
    </div>
    @if (User.IsInRole("Teacher"))
    {
        <div class="col-lg-8">
            <label class="text-danger">@Localizer["You will ony see students to which group at least one of your subject is attached"]</label>
        </div>
    }
</div>
}



<table class="table">
    <thead>
        <tr>
            <th>
                <label>@Localizer["FirstName"]</label>
            </th>
            <th>
                <label>@Localizer["LastName"]</label>
            </th>
            <th>
                <label>@Localizer["Group"]</label>
            </th>
            <th>
                <label>@Localizer["AverageGrade"]</label>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="students-data-table">
        <partial name="_StudentsTablePartial" model="Model" />
    </tbody>
</table>

SchoolRegister.Web/Views/Student/_StudentsTablePartial.cshtml
@model IEnumerable<SchoolRegister.ViewModels.VMs.StudentVM>

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GroupName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AverageGrade)
        </td>
        <td>
            @Html.ActionLink(@Localizer["GradesReport"].Value, "Index", "Grade", new { id = item.Id })
            @if (User.IsInRole("Teacher"))
            {
                @Html.Raw(" | ")
                @Html.ActionLink(@Localizer["AddGrade"].Value, "Create", "Grade", new { id = item.Id })
            }
        </td>
    </tr>
}